# Generated by Django 4.1 on 2023-02-05 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_portfolio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Portfolio',
            new_name='Work',
        ),
    ]
